
name: Ionic & Cordova Build

on:
  push:
    branches: [ master, backend-integration ]
  pull_request:
    branches: [ master, backend-integration ]

jobs:
  android:
    name: Cordova Build Android
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm ci
      env:
        NG_CLI_ANALYTICS: ci
    - name: Run Ionic Build
      run: npx ionic build
    - name: Cordova Add Android
      run: npx ionic cordova platform add android
    - name: Cordova Prepare Android
      run: npx ionic cordova prepare android
    - name: Copy google-service.json
      run: cp google-services.json platforms/android/app/
    - name: Cordova Build Android
      run: npx ionic cordova build android
    - name: Upload Debug APK
      uses: actions/upload-artifact@v1
      with:
        name: RIOD
        path: platforms/android/app/build/outputs/apk/debug/app-debug.apk

  ios:
    name: Cordova Build iOS
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm ci
      env:
        NG_CLI_ANALYTICS: ci
    - name: Run Ionic Build
      run: npx ionic build
    - name: Cordova Add iOS
      run: npx ionic cordova platform add ios
    - name: Cordova Prepare iOS
      run: npx ionic cordova prepare ios
    - name: Cordova Build iOS
      run: npx ionic cordova build ios
